(ns gpu_accelerator.actor
  "gpu_accelerator clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). GPU streaming-multiprocessor accelerator design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; Gpu
   {:db/ident :gpu_accelerator.Gpu/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gpu_accelerator.Gpu/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Gpu/architecture :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Gpu/smCount :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Gpu/vramGb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Gpu/tflops :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Gpu/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Gpu/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; StreamingMultiprocessor
   {:db/ident :gpu_accelerator.StreamingMultiprocessor/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gpu_accelerator.StreamingMultiprocessor/gpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.StreamingMultiprocessor/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.StreamingMultiprocessor/cudaCores :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.StreamingMultiprocessor/sharedMemKb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.StreamingMultiprocessor/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.StreamingMultiprocessor/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TensorCore
   {:db/ident :gpu_accelerator.TensorCore/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gpu_accelerator.TensorCore/smId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.TensorCore/generation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.TensorCore/precision :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.TensorCore/tops :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.TensorCore/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.TensorCore/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MemoryHierarchy
   {:db/ident :gpu_accelerator.MemoryHierarchy/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gpu_accelerator.MemoryHierarchy/gpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.MemoryHierarchy/level :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.MemoryHierarchy/sizeMb :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.MemoryHierarchy/bandwidthGbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.MemoryHierarchy/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.MemoryHierarchy/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Warp
   {:db/ident :gpu_accelerator.Warp/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gpu_accelerator.Warp/smId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Warp/threads :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Warp/scheduler :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Warp/occupancy :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Warp/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.Warp/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; KernelLaunch
   {:db/ident :gpu_accelerator.KernelLaunch/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :gpu_accelerator.KernelLaunch/gpuId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.KernelLaunch/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.KernelLaunch/gridDim :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.KernelLaunch/blockDim :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.KernelLaunch/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.KernelLaunch/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :gpu_accelerator.KernelLaunch/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"Gpu" "StreamingMultiprocessor" "TensorCore" "MemoryHierarchy" "Warp" "KernelLaunch"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "gpu_accelerator: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "gpu_accelerator: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "gpu_accelerator: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── Gpu ────────────────────────────────────────────────────────────────
(defn create-gpu
  "Create a Gpu."
  [port data]
  (require-fields data ["name" "architecture"])
  (let [id (new-id "gpu_gpu")
        e {:db/id id
           :gpu_accelerator.Gpu/id id
           :gpu_accelerator.Gpu/name (get data :name)
           :gpu_accelerator.Gpu/architecture (get data :architecture)
           :gpu_accelerator.Gpu/smCount (as-long (get data :smCount))
           :gpu_accelerator.Gpu/vramGb (as-long (get data :vramGb))
           :gpu_accelerator.Gpu/tflops (as-double (get data :tflops))
           :gpu_accelerator.Gpu/createdAt (now)
           :gpu_accelerator.Gpu/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-gpus
  "List Gpu with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-gpus port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gpu_accelerator.Gpu/id))
         rows (apply-filters rows (:filter opts) [:gpu_accelerator.Gpu/name :gpu_accelerator.Gpu/architecture :gpu_accelerator.Gpu/smCount :gpu_accelerator.Gpu/vramGb :gpu_accelerator.Gpu/tflops])]
     (paginate rows opts))))

(defn get-gpu
  "Retrieve a Gpu by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-gpu port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-gpu
  "Update a Gpu; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :gpu_accelerator.Gpu/name (get data :name)]))
                   (cond-> (contains? data :architecture) (conj [:db/add id :gpu_accelerator.Gpu/architecture (get data :architecture)]))
                   (cond-> (contains? data :smCount) (conj [:db/add id :gpu_accelerator.Gpu/smCount (as-long (get data :smCount))]))
                   (cond-> (contains? data :vramGb) (conj [:db/add id :gpu_accelerator.Gpu/vramGb (as-long (get data :vramGb))]))
                   (cond-> (contains? data :tflops) (conj [:db/add id :gpu_accelerator.Gpu/tflops (as-double (get data :tflops))]))
                   (conj [:db/add id :gpu_accelerator.Gpu/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-gpu
  "Delete a Gpu."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── StreamingMultiprocessor ────────────────────────────────────────────────────────────────
(defn create-streaming-multiprocessor
  "Create a StreamingMultiprocessor."
  [port data]
  (require-fields data ["index" "cudaCores"])
  (let [id (new-id "gpu_str")
        e {:db/id id
           :gpu_accelerator.StreamingMultiprocessor/id id
           :gpu_accelerator.StreamingMultiprocessor/gpuId (get data :gpuId)
           :gpu_accelerator.StreamingMultiprocessor/index (as-long (get data :index))
           :gpu_accelerator.StreamingMultiprocessor/cudaCores (as-long (get data :cudaCores))
           :gpu_accelerator.StreamingMultiprocessor/sharedMemKb (as-long (get data :sharedMemKb))
           :gpu_accelerator.StreamingMultiprocessor/createdAt (now)
           :gpu_accelerator.StreamingMultiprocessor/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-streaming-multiprocessors
  "List StreamingMultiprocessor with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-streaming-multiprocessors port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gpu_accelerator.StreamingMultiprocessor/id))
         rows (apply-filters rows (:filter opts) [:gpu_accelerator.StreamingMultiprocessor/gpuId :gpu_accelerator.StreamingMultiprocessor/index :gpu_accelerator.StreamingMultiprocessor/cudaCores :gpu_accelerator.StreamingMultiprocessor/sharedMemKb])]
     (paginate rows opts))))

(defn get-streaming-multiprocessor
  "Retrieve a StreamingMultiprocessor by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-streaming-multiprocessor port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :gpuId) (get rec :gpu_accelerator.StreamingMultiprocessor/gpuId))
         (assoc :gpuId-obj (-pull port (get rec :gpu_accelerator.StreamingMultiprocessor/gpuId))))))))

(defn update-streaming-multiprocessor
  "Update a StreamingMultiprocessor; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :gpuId) (conj [:db/add id :gpu_accelerator.StreamingMultiprocessor/gpuId (get data :gpuId)]))
                   (cond-> (contains? data :index) (conj [:db/add id :gpu_accelerator.StreamingMultiprocessor/index (as-long (get data :index))]))
                   (cond-> (contains? data :cudaCores) (conj [:db/add id :gpu_accelerator.StreamingMultiprocessor/cudaCores (as-long (get data :cudaCores))]))
                   (cond-> (contains? data :sharedMemKb) (conj [:db/add id :gpu_accelerator.StreamingMultiprocessor/sharedMemKb (as-long (get data :sharedMemKb))]))
                   (conj [:db/add id :gpu_accelerator.StreamingMultiprocessor/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-streaming-multiprocessor
  "Delete a StreamingMultiprocessor."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TensorCore ────────────────────────────────────────────────────────────────
(defn create-tensor-core
  "Create a TensorCore."
  [port data]
  (require-fields data ["generation" "precision"])
  (let [id (new-id "gpu_ten")
        e {:db/id id
           :gpu_accelerator.TensorCore/id id
           :gpu_accelerator.TensorCore/smId (get data :smId)
           :gpu_accelerator.TensorCore/generation (get data :generation)
           :gpu_accelerator.TensorCore/precision (get data :precision)
           :gpu_accelerator.TensorCore/tops (as-double (get data :tops))
           :gpu_accelerator.TensorCore/createdAt (now)
           :gpu_accelerator.TensorCore/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-tensor-cores
  "List TensorCore with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-tensor-cores port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gpu_accelerator.TensorCore/id))
         rows (apply-filters rows (:filter opts) [:gpu_accelerator.TensorCore/smId :gpu_accelerator.TensorCore/generation :gpu_accelerator.TensorCore/precision :gpu_accelerator.TensorCore/tops])]
     (paginate rows opts))))

(defn get-tensor-core
  "Retrieve a TensorCore by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-tensor-core port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-tensor-core
  "Update a TensorCore; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :smId) (conj [:db/add id :gpu_accelerator.TensorCore/smId (get data :smId)]))
                   (cond-> (contains? data :generation) (conj [:db/add id :gpu_accelerator.TensorCore/generation (get data :generation)]))
                   (cond-> (contains? data :precision) (conj [:db/add id :gpu_accelerator.TensorCore/precision (get data :precision)]))
                   (cond-> (contains? data :tops) (conj [:db/add id :gpu_accelerator.TensorCore/tops (as-double (get data :tops))]))
                   (conj [:db/add id :gpu_accelerator.TensorCore/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-tensor-core
  "Delete a TensorCore."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MemoryHierarchy ────────────────────────────────────────────────────────────────
(defn create-memory-hierarchy
  "Create a MemoryHierarchy."
  [port data]
  (require-fields data ["level" "sizeMb"])
  (let [id (new-id "gpu_mem")
        e {:db/id id
           :gpu_accelerator.MemoryHierarchy/id id
           :gpu_accelerator.MemoryHierarchy/gpuId (get data :gpuId)
           :gpu_accelerator.MemoryHierarchy/level (get data :level)
           :gpu_accelerator.MemoryHierarchy/sizeMb (as-double (get data :sizeMb))
           :gpu_accelerator.MemoryHierarchy/bandwidthGbps (as-double (get data :bandwidthGbps))
           :gpu_accelerator.MemoryHierarchy/createdAt (now)
           :gpu_accelerator.MemoryHierarchy/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-memory-hierarchies
  "List MemoryHierarchy with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-memory-hierarchies port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gpu_accelerator.MemoryHierarchy/id))
         rows (apply-filters rows (:filter opts) [:gpu_accelerator.MemoryHierarchy/gpuId :gpu_accelerator.MemoryHierarchy/level :gpu_accelerator.MemoryHierarchy/sizeMb :gpu_accelerator.MemoryHierarchy/bandwidthGbps])]
     (paginate rows opts))))

(defn get-memory-hierarchy
  "Retrieve a MemoryHierarchy by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-memory-hierarchy port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :gpuId) (get rec :gpu_accelerator.MemoryHierarchy/gpuId))
         (assoc :gpuId-obj (-pull port (get rec :gpu_accelerator.MemoryHierarchy/gpuId))))))))

(defn update-memory-hierarchy
  "Update a MemoryHierarchy; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :gpuId) (conj [:db/add id :gpu_accelerator.MemoryHierarchy/gpuId (get data :gpuId)]))
                   (cond-> (contains? data :level) (conj [:db/add id :gpu_accelerator.MemoryHierarchy/level (get data :level)]))
                   (cond-> (contains? data :sizeMb) (conj [:db/add id :gpu_accelerator.MemoryHierarchy/sizeMb (as-double (get data :sizeMb))]))
                   (cond-> (contains? data :bandwidthGbps) (conj [:db/add id :gpu_accelerator.MemoryHierarchy/bandwidthGbps (as-double (get data :bandwidthGbps))]))
                   (conj [:db/add id :gpu_accelerator.MemoryHierarchy/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-memory-hierarchy
  "Delete a MemoryHierarchy."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Warp ────────────────────────────────────────────────────────────────
(defn create-warp
  "Create a Warp."
  [port data]
  (require-fields data ["threads" "scheduler"])
  (let [id (new-id "gpu_war")
        e {:db/id id
           :gpu_accelerator.Warp/id id
           :gpu_accelerator.Warp/smId (get data :smId)
           :gpu_accelerator.Warp/threads (as-long (get data :threads))
           :gpu_accelerator.Warp/scheduler (get data :scheduler)
           :gpu_accelerator.Warp/occupancy (as-double (get data :occupancy))
           :gpu_accelerator.Warp/createdAt (now)
           :gpu_accelerator.Warp/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-warps
  "List Warp with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-warps port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gpu_accelerator.Warp/id))
         rows (apply-filters rows (:filter opts) [:gpu_accelerator.Warp/smId :gpu_accelerator.Warp/threads :gpu_accelerator.Warp/scheduler :gpu_accelerator.Warp/occupancy])]
     (paginate rows opts))))

(defn get-warp
  "Retrieve a Warp by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-warp port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-warp
  "Update a Warp; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :smId) (conj [:db/add id :gpu_accelerator.Warp/smId (get data :smId)]))
                   (cond-> (contains? data :threads) (conj [:db/add id :gpu_accelerator.Warp/threads (as-long (get data :threads))]))
                   (cond-> (contains? data :scheduler) (conj [:db/add id :gpu_accelerator.Warp/scheduler (get data :scheduler)]))
                   (cond-> (contains? data :occupancy) (conj [:db/add id :gpu_accelerator.Warp/occupancy (as-double (get data :occupancy))]))
                   (conj [:db/add id :gpu_accelerator.Warp/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-warp
  "Delete a Warp."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── KernelLaunch ────────────────────────────────────────────────────────────────
(defn create-kernel-launch
  "Create a KernelLaunch."
  [port data]
  (require-fields data ["name" "gridDim"])
  (let [id (new-id "gpu_ker")
        e {:db/id id
           :gpu_accelerator.KernelLaunch/id id
           :gpu_accelerator.KernelLaunch/gpuId (get data :gpuId)
           :gpu_accelerator.KernelLaunch/name (get data :name)
           :gpu_accelerator.KernelLaunch/gridDim (as-long (get data :gridDim))
           :gpu_accelerator.KernelLaunch/blockDim (as-long (get data :blockDim))
           :gpu_accelerator.KernelLaunch/status (get data :status)
           :gpu_accelerator.KernelLaunch/createdAt (now)
           :gpu_accelerator.KernelLaunch/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-kernel-launches
  "List KernelLaunch with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-kernel-launches port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :gpu_accelerator.KernelLaunch/id))
         rows (apply-filters rows (:filter opts) [:gpu_accelerator.KernelLaunch/gpuId :gpu_accelerator.KernelLaunch/name :gpu_accelerator.KernelLaunch/gridDim :gpu_accelerator.KernelLaunch/blockDim :gpu_accelerator.KernelLaunch/status])]
     (paginate rows opts))))

(defn get-kernel-launch
  "Retrieve a KernelLaunch by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-kernel-launch port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :gpuId) (get rec :gpu_accelerator.KernelLaunch/gpuId))
         (assoc :gpuId-obj (-pull port (get rec :gpu_accelerator.KernelLaunch/gpuId))))))))

(defn update-kernel-launch
  "Update a KernelLaunch; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :gpuId) (conj [:db/add id :gpu_accelerator.KernelLaunch/gpuId (get data :gpuId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :gpu_accelerator.KernelLaunch/name (get data :name)]))
                   (cond-> (contains? data :gridDim) (conj [:db/add id :gpu_accelerator.KernelLaunch/gridDim (as-long (get data :gridDim))]))
                   (cond-> (contains? data :blockDim) (conj [:db/add id :gpu_accelerator.KernelLaunch/blockDim (as-long (get data :blockDim))]))
                   (cond-> (contains? data :status) (conj [:db/add id :gpu_accelerator.KernelLaunch/status (get data :status)]))
                   (conj [:db/add id :gpu_accelerator.KernelLaunch/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-kernel-launch
  "Delete a KernelLaunch."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/gpus" :op :create :entity "Gpu"}
   {:method "GET" :path "/v1/gpus" :op :list :entity "Gpu"}
   {:method "GET" :path "/v1/gpus/:id" :op :get :entity "Gpu"}
   {:method "PATCH" :path "/v1/gpus/:id" :op :update :entity "Gpu"}
   {:method "DELETE" :path "/v1/gpus/:id" :op :delete :entity "Gpu"}
   {:method "POST" :path "/v1/streamingmultiprocessors" :op :create :entity "StreamingMultiprocessor"}
   {:method "GET" :path "/v1/streamingmultiprocessors" :op :list :entity "StreamingMultiprocessor"}
   {:method "GET" :path "/v1/streamingmultiprocessors/:id" :op :get :entity "StreamingMultiprocessor"}
   {:method "PATCH" :path "/v1/streamingmultiprocessors/:id" :op :update :entity "StreamingMultiprocessor"}
   {:method "DELETE" :path "/v1/streamingmultiprocessors/:id" :op :delete :entity "StreamingMultiprocessor"}
   {:method "POST" :path "/v1/tensorcores" :op :create :entity "TensorCore"}
   {:method "GET" :path "/v1/tensorcores" :op :list :entity "TensorCore"}
   {:method "GET" :path "/v1/tensorcores/:id" :op :get :entity "TensorCore"}
   {:method "PATCH" :path "/v1/tensorcores/:id" :op :update :entity "TensorCore"}
   {:method "DELETE" :path "/v1/tensorcores/:id" :op :delete :entity "TensorCore"}
   {:method "POST" :path "/v1/memoryhierarchies" :op :create :entity "MemoryHierarchy"}
   {:method "GET" :path "/v1/memoryhierarchies" :op :list :entity "MemoryHierarchy"}
   {:method "GET" :path "/v1/memoryhierarchies/:id" :op :get :entity "MemoryHierarchy"}
   {:method "PATCH" :path "/v1/memoryhierarchies/:id" :op :update :entity "MemoryHierarchy"}
   {:method "DELETE" :path "/v1/memoryhierarchies/:id" :op :delete :entity "MemoryHierarchy"}
   {:method "POST" :path "/v1/warps" :op :create :entity "Warp"}
   {:method "GET" :path "/v1/warps" :op :list :entity "Warp"}
   {:method "GET" :path "/v1/warps/:id" :op :get :entity "Warp"}
   {:method "PATCH" :path "/v1/warps/:id" :op :update :entity "Warp"}
   {:method "DELETE" :path "/v1/warps/:id" :op :delete :entity "Warp"}
   {:method "POST" :path "/v1/kernellaunches" :op :create :entity "KernelLaunch"}
   {:method "GET" :path "/v1/kernellaunches" :op :list :entity "KernelLaunch"}
   {:method "GET" :path "/v1/kernellaunches/:id" :op :get :entity "KernelLaunch"}
   {:method "PATCH" :path "/v1/kernellaunches/:id" :op :update :entity "KernelLaunch"}
   {:method "DELETE" :path "/v1/kernellaunches/:id" :op :delete :entity "KernelLaunch"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"gpus" {:create create-gpu :list list-gpus :get get-gpu :update update-gpu :delete delete-gpu}
   "streamingmultiprocessors" {:create create-streaming-multiprocessor :list list-streaming-multiprocessors :get get-streaming-multiprocessor :update update-streaming-multiprocessor :delete delete-streaming-multiprocessor}
   "tensorcores" {:create create-tensor-core :list list-tensor-cores :get get-tensor-core :update update-tensor-core :delete delete-tensor-core}
   "memoryhierarchies" {:create create-memory-hierarchy :list list-memory-hierarchies :get get-memory-hierarchy :update update-memory-hierarchy :delete delete-memory-hierarchy}
   "warps" {:create create-warp :list list-warps :get get-warp :update update-warp :delete delete-warp}
   "kernellaunches" {:create create-kernel-launch :list list-kernel-launches :get get-kernel-launch :update update-kernel-launch :delete delete-kernel-launch}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "gpu_accelerator-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
